project:
  type: website
  output-dir: docs

website:
  title: "Data Science with R"
  repo-url: https://github.com/astamm/data-science-with-r/
  repo-actions: [edit, source, issue]
  page-footer:
    background: light
    left: Copyright 2024, Aymeric Stamm
    right: This website is built with [Quarto](https://quarto.org/)
  navbar:
    left:
      - text: "Slides"
        menu:
          - text: "Introduction"
            href: 01_Introduction/01-Introduction-Slides.pdf
          - text: "Visualize"
            href: 02_Visualize/02-Visualize-Slides.pdf
      - text: "Labs"
        menu:
          - text: "Introduction"
            href: 01_Introduction/01-Introduction-Exercises.qmd
          - text: "Visualize"
            href: 02_Visualize/02-Visualize-Exercises.qmd
    right:
      - icon: github
        href: https://github.com/astamm/data-science-with-r/

  search:
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
